'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ceidgapi
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Ceidgapi.IDataStoreProvider201901")>  _
    Public Interface IDataStoreProvider201901
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDataStoreProvider201901/GetID", ReplyAction:="http://tempuri.org/IDataStoreProvider201901/GetIDResponse")>  _
        Function GetID(ByVal AuthToken As String, ByVal DateFrom As System.Nullable(Of Date), ByVal DateTo As System.Nullable(Of Date), ByVal MigrationDateFrom As System.Nullable(Of Date), ByVal MigrationDateTo As System.Nullable(Of Date)) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDataStoreProvider201901/GetID", ReplyAction:="http://tempuri.org/IDataStoreProvider201901/GetIDResponse")>  _
        Function GetIDAsync(ByVal AuthToken As String, ByVal DateFrom As System.Nullable(Of Date), ByVal DateTo As System.Nullable(Of Date), ByVal MigrationDateFrom As System.Nullable(Of Date), ByVal MigrationDateTo As System.Nullable(Of Date)) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDataStoreProvider201901/GetMigrationData201901", ReplyAction:="http://tempuri.org/IDataStoreProvider201901/GetMigrationData201901Response")>  _
        Function GetMigrationData201901( _
                    ByVal AuthToken As String,  _
                    ByVal NIP() As String,  _
                    ByVal REGON() As String,  _
                    ByVal NIP_SC() As String,  _
                    ByVal REGON_SC() As String,  _
                    ByVal Name() As String,  _
                    ByVal Province() As String,  _
                    ByVal County() As String,  _
                    ByVal Commune() As String,  _
                    ByVal City() As String,  _
                    ByVal Street() As String,  _
                    ByVal Postcode() As String,  _
                    ByVal DateFrom As System.Nullable(Of Date),  _
                    ByVal DateTo As System.Nullable(Of Date),  _
                    ByVal PKD() As String,  _
                    ByVal status() As Integer,  _
                    ByVal UniqueId() As String,  _
                    ByVal MigrationDateFrom As System.Nullable(Of Date),  _
                    ByVal MigrationDateTo As System.Nullable(Of Date)) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDataStoreProvider201901/GetMigrationData201901", ReplyAction:="http://tempuri.org/IDataStoreProvider201901/GetMigrationData201901Response")>  _
        Function GetMigrationData201901Async( _
                    ByVal AuthToken As String,  _
                    ByVal NIP() As String,  _
                    ByVal REGON() As String,  _
                    ByVal NIP_SC() As String,  _
                    ByVal REGON_SC() As String,  _
                    ByVal Name() As String,  _
                    ByVal Province() As String,  _
                    ByVal County() As String,  _
                    ByVal Commune() As String,  _
                    ByVal City() As String,  _
                    ByVal Street() As String,  _
                    ByVal Postcode() As String,  _
                    ByVal DateFrom As System.Nullable(Of Date),  _
                    ByVal DateTo As System.Nullable(Of Date),  _
                    ByVal PKD() As String,  _
                    ByVal status() As Integer,  _
                    ByVal UniqueId() As String,  _
                    ByVal MigrationDateFrom As System.Nullable(Of Date),  _
                    ByVal MigrationDateTo As System.Nullable(Of Date)) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IDataStoreProvider201901Channel
        Inherits Ceidgapi.IDataStoreProvider201901, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DataStoreProvider201901Client
        Inherits System.ServiceModel.ClientBase(Of Ceidgapi.IDataStoreProvider201901)
        Implements Ceidgapi.IDataStoreProvider201901
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetID(ByVal AuthToken As String, ByVal DateFrom As System.Nullable(Of Date), ByVal DateTo As System.Nullable(Of Date), ByVal MigrationDateFrom As System.Nullable(Of Date), ByVal MigrationDateTo As System.Nullable(Of Date)) As String Implements Ceidgapi.IDataStoreProvider201901.GetID
            Return MyBase.Channel.GetID(AuthToken, DateFrom, DateTo, MigrationDateFrom, MigrationDateTo)
        End Function
        
        Public Function GetIDAsync(ByVal AuthToken As String, ByVal DateFrom As System.Nullable(Of Date), ByVal DateTo As System.Nullable(Of Date), ByVal MigrationDateFrom As System.Nullable(Of Date), ByVal MigrationDateTo As System.Nullable(Of Date)) As System.Threading.Tasks.Task(Of String) Implements Ceidgapi.IDataStoreProvider201901.GetIDAsync
            Return MyBase.Channel.GetIDAsync(AuthToken, DateFrom, DateTo, MigrationDateFrom, MigrationDateTo)
        End Function
        
        Public Function GetMigrationData201901( _
                    ByVal AuthToken As String,  _
                    ByVal NIP() As String,  _
                    ByVal REGON() As String,  _
                    ByVal NIP_SC() As String,  _
                    ByVal REGON_SC() As String,  _
                    ByVal Name() As String,  _
                    ByVal Province() As String,  _
                    ByVal County() As String,  _
                    ByVal Commune() As String,  _
                    ByVal City() As String,  _
                    ByVal Street() As String,  _
                    ByVal Postcode() As String,  _
                    ByVal DateFrom As System.Nullable(Of Date),  _
                    ByVal DateTo As System.Nullable(Of Date),  _
                    ByVal PKD() As String,  _
                    ByVal status() As Integer,  _
                    ByVal UniqueId() As String,  _
                    ByVal MigrationDateFrom As System.Nullable(Of Date),  _
                    ByVal MigrationDateTo As System.Nullable(Of Date)) As String Implements Ceidgapi.IDataStoreProvider201901.GetMigrationData201901
            Return MyBase.Channel.GetMigrationData201901(AuthToken, NIP, REGON, NIP_SC, REGON_SC, Name, Province, County, Commune, City, Street, Postcode, DateFrom, DateTo, PKD, status, UniqueId, MigrationDateFrom, MigrationDateTo)
        End Function
        
        Public Function GetMigrationData201901Async( _
                    ByVal AuthToken As String,  _
                    ByVal NIP() As String,  _
                    ByVal REGON() As String,  _
                    ByVal NIP_SC() As String,  _
                    ByVal REGON_SC() As String,  _
                    ByVal Name() As String,  _
                    ByVal Province() As String,  _
                    ByVal County() As String,  _
                    ByVal Commune() As String,  _
                    ByVal City() As String,  _
                    ByVal Street() As String,  _
                    ByVal Postcode() As String,  _
                    ByVal DateFrom As System.Nullable(Of Date),  _
                    ByVal DateTo As System.Nullable(Of Date),  _
                    ByVal PKD() As String,  _
                    ByVal status() As Integer,  _
                    ByVal UniqueId() As String,  _
                    ByVal MigrationDateFrom As System.Nullable(Of Date),  _
                    ByVal MigrationDateTo As System.Nullable(Of Date)) As System.Threading.Tasks.Task(Of String) Implements Ceidgapi.IDataStoreProvider201901.GetMigrationData201901Async
            Return MyBase.Channel.GetMigrationData201901Async(AuthToken, NIP, REGON, NIP_SC, REGON_SC, Name, Province, County, Commune, City, Street, Postcode, DateFrom, DateTo, PKD, status, UniqueId, MigrationDateFrom, MigrationDateTo)
        End Function
    End Class
End Namespace
